### ISSUE TITLE
Log Level

### ISSUE THREAD

**Issue by kusmierz** [clearflask/clearflask#126]
Hi, how can I change the log level of the server as it generates a lot of DEBUG and TRACE messages. I have tried adding `- JAVA_OPTS="-Dorg.slf4j.simpleLogger.defaultLogLevel=WARN -Dlog4j.rootLogger=WARN"` to docker environments but to no luck. I'm using `docker-compose.self-host.yml`.

**Comment by matusfaro** [comment]
Ah I was bundling the wrong logging config and it was logging at TRACE level rather than INFO. You have two options:

1. Pull in the latest version 1.6.10 with my fix which raises it to INFO level which is not noisy.
2. Override the logging configuration:
  a) Download https://github.com/clearflask/clearflask/blob/master/clearflask-server/src/main/resources/logback-selfhost.xml and name it logback.xml
  b) Set the log level to what you need `<root level="INFO">`, valid options: TRACE, DEBUG INFO WARN ERROR
  c) In your docker compose file, add a new volume entry for clearflask server:
```
  clearflask-server:
    ...
    volumes:
      - ./logback.xml:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/logback.xml
```
