### ISSUE TITLE
Cannot add more than 10 tags

### ISSUE THREAD

**Issue by haogeek** [clearflask/clearflask#132]
When adding more than 10 tags to a category in admin dashboard, the dashboard UI will start having some confusions and when click PUBLISH button it will raise error **Connection failure processing configSetAdmin**. Then when refresh the page another error **Connection failure processing configGetAllAndUserBindAllAdmin** will raise and the dashboard could never be accessible again even after restarting the services. That means this bug will break the whole site.

**Comment by LordGaav** [comment]
I seem to have a similar issue, I have two tag groups: one with 9 tags, and one with 1 tag. When adding another tag to the second group, I get a "Something went wrong" modal but no error in the logs. I can't seem to find any indication about there being a limit of 10 tags on the Pricing page or in the docs.

**Comment by haogeek** [comment]
@LordGaav yes the next time I also get the error feedback modal dialog without the error message. The good news is in this case the site won't break.

**Comment by matusfaro** [comment]
Found the issue, fix will be in version 1.6.13

For curiosity: The problem was the logic would insert a new tag at the end, refresh the array and then attempt to initialize the tag assumed to be at the end. Unfortunately as part of the array refresh, it would also be sorted. So the autogenerated name `Tag X` would eventually hit 10 which would be sorted and placed between `Tag 1` and `Tag 2` rather than at the end. So the initialization would be performed on the wrong tag and the array would leave an undefined entry. If you managed to save that into the database, it would break any call to fetch it. You could edit it in the database to fix it by removing the null entry.
