### ISSUE TITLE
Some more confusions about voting and comment

### ISSUE THREAD

**Issue by haogeek** [clearflask/clearflask#133]
1. When using "I want this" instead of simple arrow, it will not show the voting count, and the be-lit-on button will return to grey after refreshing, is this an expected behavior? Why?
2. When adding comment, the comment itself will automatically has one upvote, is this an expected behavior? Why?
3. When deleting a comment, the comment will be marked as deleted and still be shown at its original place, and there's no way to completely remove/clear it, is this an expected behavior? Why?
4. There's no cancel button when editing a comment, I think the simple way could be clicking any blank area to exit editing mode without saving it.

I found clearflask is powerful but really needs more documents to explain its design, especially for these puzzling things, thanks.

**Comment by matusfaro** [comment]
Agreed that documentation is lacking, feel free to ask here for any clarification.


> When using "I want this" instead of simple arrow, it will not show the voting count

This is mostly a preference. Product Managers will tell you that simple voting systems are bad for understanding customers. The "I want this" button is based on more modern practices that attempt to not bias the customer prior to receiving feedback.

> and the be-lit-on button will return to grey after refreshing, is this an expected behavior? Why?

If you're talking about this button:
<img width="111" alt="image" src="https://github.com/clearflask/clearflask/assets/4206738/260f3fd0-cafa-4876-997b-93d7419e192c">
It's suppose to stay green even after you refresh. If it doesn't that's a bug. If you are logged in, click the Want button turning it green, it should stay green as long as you are logged in with the same account.

> When adding comment, the comment itself will automatically has one upvote, is this an expected behavior? Why?

Yes, you automatically upvote your own comment. This is in line with Reddit behavior and assumed to be general knowledge. To be honest, you could argue that we could prevent upvoting your own comment and just start at 0 and I think I would've made that choice If I did it again. 

> When deleting a comment, the comment will be marked as deleted and still be shown at its original place, and there's no way to completely remove/clear it, is this an expected behavior? Why?

This is because that comment potentially could have sibling comments which we don't want to delete. A future improvement could be to delete a comment entirely if it doesn't have any siblings.

> There's no cancel button when editing a comment, I think the simple way could be clicking any blank area to exit editing mode without saving it.

That makes sense. It's a bit complicated since if you make edits, you don't want to discard those changes when you lose focus, so a cancel button would be better.

---

If you want to see any changes, PRs are super welcome! I also work for hire as well. If you are using the Cloud service, I am open to adding new features as well.

**Comment by haogeek** [comment]
Thanks for your kindly response. As you've detailedly explained all the underlying thoughts, I think it's OK to have these interactive experience.

I agree that people don't want to lose unsaved comment, so adding a cancel button would be better. And I think the logic could be: when losing focus the unsaved content will stay in the editor, when submitting a new comment will be added, when canceling the unsaved content will lose.

**Comment by haogeek** [comment]
@matusfaro I tested again and the voting status really has a little bug, no matter using voting arrow or "I want this" button it always has this bug:

When upvoting an Idea (the subject post), the arrow or the button will turn to green, then I switch to another page and switch back using tabs and this status will stay as green, but when I refresh the same page, the voting status will return to grey. If I switch to another page and do refresh on there, then switch back, the green status appears again. So in short, refreshing will remove the green status on the same page, but will recover green status on other pages. To be clear, only the color of the voting status changes, the underlying voting record and voting count does not change.

I tested on feedback page with Explorer or Collect Feedback layout and inside the Idea detail page, all got the same result. And roadmap also has this problem.

However, voting on comment does not have this issue, the status is always correct. What's more, when using search/filter, the results hold correct voting status too. And in dashboard when I click and open a detail dialog of any Idea/Roadmap task, the voting status is also correct. Besides, I didn't see same behavior on ClearFlask official site.
