### ISSUE TITLE
ScyllaDB will fail due to unsupported TransactWriteItems operation

### ISSUE THREAD

**Issue by haogeek** [clearflask/clearflask#142]
The readme document recommended using ScyllaDB as an alternative of AWS DynamoDB, so I tried but got the following error:

> com.amazonaws.services.dynamodbv2.model.AmazonDynamoDBException: Unsupported operation TransactWriteItems (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: UnknownOperationException; Request ID: null; Proxy: null)

I found that ScyllaDB indeed didn't implement some of the DynamoDB API, including this TransactWriteItems
(see https://opensource.docs.scylladb.com/stable/alternator/compatibility.html#unimplemented-api-features)

So I have to use either AWS official services or localstack. ClearFlask is still under evaluation in my team so AWS might not be an affordable way.

I'm not sure if it's a bug and whether clearflask is still compatible with ScyllaDB, as the error message came from aws package, I guess it might because the package had been updated when rebuilding the docker image and it will use these new APIs.

**Comment by matusfaro** [comment]
Unfortunately I don't actively test/support ScyllaDB. (although PRs are welcome).

I will remove it from the README for now.

In the meantime you can use Localstack, just make sure you follow the version described in the Docker Compose file since recent versions no longer support persistance of data in the community version.
