### ISSUE TITLE
Unable to signup with admin@localhost

### ISSUE THREAD

**Issue by duckhunter392** [clearflask/clearflask#19]
I have setup clearflask using docker on a remote Ubuntu 20.04 machine. I am able to get it started and access the login page from my Windows PC by pointing to the IP address of the Ubuntu machine. When I go make an account, I use the admin@localhost email and it redirects to /dashboard. However, the /dashboard page never loads and I get the error "Action not allowed, please refresh and try again" displayed in the bottom left corner of the page. I have tried refreshing the page, restarting the docker containers, reinstalling clearflask, and changing the super admin regex in the config to a different email. None of these have fixed the issue.

When I run clearflask on Windows locally, I am able to access the login page using `localhost` and it lets me create an account using admin@localhost as intended. It seems like the only way to login as a super admin for the initial setup is by accessing the site locally. I am unable to do this with my setup on Ubuntu 20.04 because it's CLI based. I'm not sure if this is a bug or a security feature... if it is a security feature then a config option to disable this would be appreciated!

**Comment by matusfaro** [comment]
Default installlation assumes it is hosted locally and assumes `localhost` as its hostname. It seems like the frontend can't talk to the backend as it tries to connect to localhost. You can confirm this by opening your browser Inspector and clickign on the Network tab to see whether requests are going to `localhost`.

To fix this, please try to set these two configs:
File `connect.config.json` config `parentDomain` to `yoursite.com`
File `config-selfhost.cfg` config `com.smotana.clearflask.web.Application$Config.domain` to `yoursite.com`

I haven't tested setting this as an IP address, if that's what you need, please try it and let me know if it doesn't work and also if it works as well, I'd like to know :)

If you want to setup automatic TLS certificates, you can set a few additional configs [here](https://github.com/clearflask/clearflask/blob/master/INSTALLATION.md#dns-and-certificates).

Thank you for submitting an issue here, I will make the documentation clearer.

**Comment by duckhunter392** [comment]
Thank you for the quick reply! It looks like I forgot to set the `connect.config.json` file. I set this, but it looks like the error still persists. I went ahead and switched from pointing to IP addresses to using a domain name (I'll test the IP address later to see if this works).

I checked the network tab in my browsers inspector and it looks like all of the request URL's are properly going to the domain name I set. I did notice though that there's an error in the network tab: 
![image](https://user-images.githubusercontent.com/17309033/142974519-42154702-8c1b-4a70-b3cc-5fee50eaeb32.png)

Any ideas about this one?

**Comment by matusfaro** [comment]
I was able to reproduce this. The issue is that the auth cookies are using `secure=true`, meaning it expects to use HTTPS or to be running on `localhost`. I am making this configurable so you can run it without HTTPS. So your options are:

1. Continue using HTTP and wait a few hours until I release a minor update version `1.5.0` that will allow you to set the following config:
 `config-selfhost.cfg:com.smotana.clearflask.web.security.AuthCookieImpl$Config.authCookieSecure=false`
2. Use HTTPS using either:
  a) For installations in private networks, setup your own reverse proxy with TLS termination and own certificate and [configure ClearFlask](https://github.com/clearflask/clearflask/blob/master/INSTALLATION.md#self-managed-behind-reverse-proxy)
  b) For publicly reachable site, use [built-in Let's Encrypt management](https://github.com/clearflask/clearflask/blob/master/INSTALLATION.md#automagic-using-lets-encrypt)

**Comment by duckhunter392** [comment]
Much appreciated for the prompt assistance with this. I'll give this a try a bit later and see what we get!
